import { defineNuxtPlugin } from '#app';
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

import {
  faBars,
  faEye,
  faSearch,
  faPenSquare,
  faMusic,
  faSignOutAlt,
  faHeart,
  faUserAlt,
  faGuitar,
  faPlusSquare,
  faEdit,
  faStar,
  faHistory,
  faClipboard,
  faClipboardList,
  faQuestionCircle,
  faPlayCircle,
  faHeadphones,
  faVolumeUp,
  faArrowLeft,
  faTrashAlt,
  faMoon,
  faSun,
  faMapPin,
  faCheckSquare,
  faSave,
  faLock,
  faEnvelope,
  faAngleRight,
  faAngleLeft,
  faStickyNote,
  faArrowUp,
  faEyeSlash,
  faLockOpen,
  faPauseCircle,
  faMinus,
  faPlus,
  faDrum,
  faListUl,
  faUsers,
  faChevronDown,
  faChevronUp,
  faEllipsisV,
  faTimes,
  faCheckCircle,
  faExclamationCircle,
  faPen,
  faSortAmountDownAlt,
  faCog,
  faChevronLeft,
  faChevronRight,
  faSearchMinus,
} from '@fortawesome/free-solid-svg-icons';

import {
  faHeart as HeartRegular,
  faCopy,
  faTimesCircle,
} from '@fortawesome/free-regular-svg-icons';


library.add(
  faBars,
  faEye,
  faSearch,
  faPenSquare,
  faMusic,
  faSignOutAlt,
  faHeart,
  faUserAlt,
  faGuitar,
  faPlusSquare,
  faEdit,
  faStar,
  faHistory,
  faClipboard,
  faClipboardList,
  faQuestionCircle,
  faPlayCircle,
  faHeadphones,
  faVolumeUp,
  faArrowLeft,
  faTrashAlt,
  HeartRegular,
  faMoon,
  faSun,
  faMapPin,
  faTimesCircle,
  faCheckSquare,
  faSave,
  faLock,
  faEnvelope,
  faAngleRight,
  faAngleLeft,
  faStickyNote,
  faArrowUp,
  faEyeSlash,
  faLockOpen,
  faPauseCircle,
  faMinus,
  faPlus,
  faDrum,
  faListUl,
  faUsers,
  faChevronDown,
  faChevronUp,
  faEllipsisV,
  faTimes,
  faCheckCircle,
  faExclamationCircle,
  faPen,
  faSortAmountDownAlt,
  faCog,
  faChevronLeft,
  faChevronRight,
  faCopy,
  faSearchMinus
);

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon);
});
